import type { Product } from "../../lib/types"

export const mockProducts: Product[] = [
  { 
    id: 'tray-black', 
    title: 'Tray Table', 
    color: 'Black', 
    price: 99, 
    oldPrice: 200,
    discount: 50,
    isNew: true,
    countStar: 5,
    imageUrlPng: '/img/tray-black.png', 
    imageUrlWebp: '/img/tray-black.webp',
    url: 'product/tray-black',
  },
  { 
    id: 'tray-red', 
    title: 'Tray Table', 
    color: 'Red', 
    price: 99, 
    oldPrice: 200,
    discount: 50,
    isNew: true,
    countStar: 5,
    imageUrlPng: '/img/tray-red.png', 
    imageUrlWebp: '/img/tray-red.webp',
    url: 'product/tray-red',
  },
  { 
    id: 'lamp-gold', 
    title: 'Table lamp', 
    color: 'Gold', 
    price: 39,
    countStar: 5,
    imageUrlPng: '/img/lamp-1.png', 
    imageUrlWebp: '/img/lamp-1.webp',
    url: 'product/lamp-gold',
  },
  { 
    id: 'sofa-dark', 
    title: 'Loveseat Sofa', 
    color: 'Grey', 
    price: 199,
    oldPrice: 400,
    countStar: 5,
    discount: 50,
    imageUrlPng: '/img/sofa-2.png', 
    imageUrlWebp: '/img/sofa-2.webp',
    url: 'product/sofa-dark',
  },
  { 
    id: 'lamp-beige', 
    title: 'Beige Table Lamp', 
    color: 'Beige', 
    price: 24.99,
    isNew: true,
    countStar: 5,
    imageUrlPng: '/img/lamp-2.png', 
    imageUrlWebp: '/img/lamp-2.webp',
    url: 'product/lamp-beige',
  },
  { 
    id: 'bamboo-basket', 
    title: 'Bamboo basket', 
    color: 'Beige', 
    price: 19.99,
    oldPrice: 40,
    discount: 50,
    isNew: true,
    countStar: 5,
    imageUrlPng: '/img/basket-1.png', 
    imageUrlWebp: '/img/basket-1.webp',
    url: 'product/bamboo-basket',
  },
  { 
    id: 'grey-toaster', 
    title: 'Toasted', 
    color: 'Grey', 
    price: 39.99,
    oldPrice: 80,
    discount: 50,
    isNew: true,
    countStar: 5,
    imageUrlPng: '/img/toaster-1.png', 
    imageUrlWebp: '/img/toaster-1.webp',
    url: 'product/grey-toaster',
  },
  { 
    id: 'grey-sofa', 
    title: 'Luxury Sofa', 
    color: 'Grey', 
    price: 299.99,
    oldPrice: 400,
    discount: 50,
    isNew: true,
    countStar: 5,
    imageUrlPng: '/img/sofa-1.png', 
    imageUrlWebp: '/img/sofa-1.webp',
    url: 'product/grey-sofa',
  },
  { 
    id: 'white-drawer', 
    title: 'White Drawer unit', 
    color: 'White', 
    price: 89.99,
    isNew: true,
    countStar: 5,
    imageUrlPng: '/img/nightstand-2.png', 
    imageUrlWebp: '/img/nightstand-2.webp',
    url: 'product/white-drawer',
  },
  { 
    id: 'bamboo-drawer', 
    title: 'Bamboo Drawer', 
    color: 'White', 
    price: 14.99,
    oldPrice: 30,
    discount: 50,
    isNew: true,
    countStar: 5,
    imageUrlPng: '/img/nightstand-1.png', 
    imageUrlWebp: '/img/nightstand-1.webp',
    url: 'product/grey-sofa',
  },
  { 
    id: 'table-lamp-mini', 
    title: 'Table Lamp', 
    color: 'Gold', 
    price: 19.99,
    oldPrice: 40,
    discount: 50,
    isNew: true,
    countStar: 5,
    imageUrlPng: '/img/lamp-1.png', 
    imageUrlWebp: '/img/lamp-1.webp',
    url: 'product/table-lamp-mini',
  },
  { 
    id: 'table-lamp', 
    title: 'Table Lamp', 
    color: 'Gold', 
    price: 19.99,
    oldPrice: 40,
    discount: 50,
    countStar: 5,
    imageUrlPng: '/img/lamp-2.png', 
    imageUrlWebp: '/img/lamp-2.webp',
    url: 'product/table-lamp-mini',
  },
  { 
    id: 'big-lamp', 
    title: 'Lamp', 
    color: 'White', 
    price: 59.99,
    isNew: true,
    countStar: 5,
    imageUrlPng: '/img/lamp-3.png', 
    imageUrlWebp: '/img/lamp-3.webp',
    url: 'product/big-lamp',
  },
  { 
    id: 'cozy-sofa', 
    title: 'Cozy Sofa', 
    color: 'Beige', 
    price: 119.99,
    oldPrice: 240,
    discount: 50,
    countStar: 5,
    imageUrlPng: '/img/sofa-3.png', 
    imageUrlWebp: '/img/sofa-3.webp',
    url: 'product/cozy-sofa',
  },
  { 
    id: 'black-table', 
    title: 'Black Brow Side table', 
    color: 'Black', 
    price: 16.99,
    oldPrice: 34,
    isNew: true,
    discount: 50,
    countStar: 5,
    imageUrlPng: '/img/table-1.png', 
    imageUrlWebp: '/img/table-1.webp',
    url: 'product/black-table',
  },
  { 
    id: 'light-pillow', 
    title: 'Light Beige Pillow', 
    color: 'Beige', 
    price: 3.99,
    isNew: true,
    countStar: 5,
    imageUrlPng: '/img/pillow-1.png', 
    imageUrlWebp: '/img/pillow-1.webp',
    url: 'product/light-pillow',
  },
  { 
    id: 'off-white-pillow', 
    title: 'Off-white Pillow', 
    color: 'Beige', 
    price: 3.99,
    isNew: true,
    countStar: 5,
    imageUrlPng: '/img/pillow-2.png', 
    imageUrlWebp: '/img/pillow-2.webp',
    url: 'product/off-white-pillow',
  },
]